In [19]:
import numpy as np

In [20]:
my_list= [1,2,3,4,5,6]

In [21]:
my_list

[1, 2, 3, 4, 5, 6]

In [22]:
np.array(my_list)

array([1, 2, 3, 4, 5, 6])

In [23]:
arr = np.array(my_list)

In [24]:
arr

array([1, 2, 3, 4, 5, 6])

In [25]:
arr.shape

(6,)

In [26]:
arr

array([1, 2, 3, 4, 5, 6])


## Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.


Import NumPy as np

In [29]:
#Create an array of 10 zeros

np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
#Create an array of 10 ones

np.ones(10, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [33]:
#Create an array of the integers from 10 to 50

np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [34]:
#Create an array of all the even integers from 10 to 50

np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [37]:
#Create a 3x3 matrix with values ranging from 0 to 8

arr = np.arange(0,9)

In [38]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
#Create a 3x3 identity matrix

np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [47]:
#Use NumPy to generate a random number between 0 and 1

np.random.rand()

0.4871732238745323

k

In [48]:
i = 1
while True:
    if i % 7 == 0:
        break
    print(i)
    i+=1

1
2
3
4
5
6


In [49]:
l = [1,2,3,4]
l[:-1]

[1, 2, 3]

In [50]:
def f(x):
    return bool(x%2)
print(f(20), f(21))

False True


In [51]:
print("%.2f"%56.236)

56.24


In [63]:
a = [1,2,3]
b= [3,4,5]